# Generated by Django 5.2.4 on 2025-08-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_name', models.CharField(default='Unknown Project', max_length=200)),
                ('fuel_type', models.CharField(choices=[('hydro', 'Hydro'), ('thermal', 'Thermal'), ('solar', 'Solar'), ('wind', 'Wind'), ('other', 'Other')], default='hydro', max_length=50)),
                ('unit_number', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_mw', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predict.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField()),
                ('predicted_fault', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('model_version', models.CharField(max_length=50)),
                ('status', models.CharField(default='open', max_length=20)),
                ('severity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predict.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(default=1, max_length=100)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('acknowledged', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predict.prediction')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=100)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predict.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Predict.sensor'),
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predict.sensor')),
            ],
        ),
    ]
