# Generated by Django 5.2.4 on 2025-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='type',
        ),
        migrations.AddField(
            model_name='equipment',
            name='capacity_mw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='fuel_type',
            field=models.CharField(choices=[('hydro', 'Hydro'), ('thermal', 'Thermal'), ('solar', 'Solar'), ('wind', 'Wind'), ('other', 'Other')], default='hydro', max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='project_name',
            field=models.CharField(default='Unknown Project', max_length=200),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
